---
apiVersion: v1
kind: ReplicationController
metadata:
  name: linkerd-viz
  labels:
    name: linkerd-viz
spec:
  replicas: 1
  selector:
    name: linkerd-viz
  template:
    metadata:
      labels:
        name: linkerd-viz
    spec:
      containers:
      - name: linkerd-viz
        image: buoyantio/linkerd-k8s-viz:0.0.1
        imagePullPolicy: Always
        env:
        - name: PUBLIC_PORT
          value: "3000"
        - name: STATS_PORT
          value: "9090"
        ports:
        - name: grafana
          containerPort: 3000
        - name: prometheus
          containerPort: 9090

      - name: kubectl
        image: buoyantio/kubectl:1.2.3
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-viz
  labels:
    name: linkerd-viz
spec:
  type: LoadBalancer
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
  - name: prometheus
    port: 9090
    targetPort: 9090
  selector:
    name: linkerd-viz
