// Code generated by protoc-gen-go.
// source: proto/word/word.proto
// DO NOT EDIT!

/*
Package word is a generated protocol buffer package.

It is generated from these files:
	proto/word/word.proto

It has these top-level messages:
	WordRequest
	WordResponse
*/
package word

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type WordRequest struct {
}

func (m *WordRequest) Reset()                    { *m = WordRequest{} }
func (m *WordRequest) String() string            { return proto.CompactTextString(m) }
func (*WordRequest) ProtoMessage()               {}
func (*WordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WordResponse struct {
	Word string `protobuf:"bytes,1,opt,name=word" json:"word,omitempty"`
}

func (m *WordResponse) Reset()                    { *m = WordResponse{} }
func (m *WordResponse) String() string            { return proto.CompactTextString(m) }
func (*WordResponse) ProtoMessage()               {}
func (*WordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*WordRequest)(nil), "word.WordRequest")
	proto.RegisterType((*WordResponse)(nil), "word.WordResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for WordSvc service

type WordSvcClient interface {
	GetWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordResponse, error)
}

type wordSvcClient struct {
	cc *grpc.ClientConn
}

func NewWordSvcClient(cc *grpc.ClientConn) WordSvcClient {
	return &wordSvcClient{cc}
}

func (c *wordSvcClient) GetWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordResponse, error) {
	out := new(WordResponse)
	err := grpc.Invoke(ctx, "/word.WordSvc/GetWord", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WordSvc service

type WordSvcServer interface {
	GetWord(context.Context, *WordRequest) (*WordResponse, error)
}

func RegisterWordSvcServer(s *grpc.Server, srv WordSvcServer) {
	s.RegisterService(&_WordSvc_serviceDesc, srv)
}

func _WordSvc_GetWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSvcServer).GetWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word.WordSvc/GetWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSvcServer).GetWord(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "word.WordSvc",
	HandlerType: (*WordSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWord",
			Handler:    _WordSvc_GetWord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xcf, 0x2f, 0x4a, 0x01, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xc4,
	0xcb, 0xc5, 0x1d, 0x0e, 0xa4, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x94, 0xb8, 0x78,
	0x20, 0xdc, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0xb0, 0x32, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x30, 0xdb, 0xc8, 0x96, 0x8b, 0x1d, 0xa4, 0x26, 0xb8, 0x2c, 0x59, 0xc8,
	0x88, 0x8b, 0xdd, 0x3d, 0xb5, 0x04, 0xc4, 0x13, 0x12, 0xd4, 0x03, 0x9b, 0x8d, 0x64, 0x98, 0x94,
	0x10, 0xb2, 0x10, 0xc4, 0x40, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xf5, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0a, 0x89, 0x1e, 0xa0, 0x97, 0x00, 0x00, 0x00,
}
