// Code generated by protoc-gen-go.
// source: helloworld.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	SvcRequest
	SvcResponse
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SvcRequest struct {
}

func (m *SvcRequest) Reset()                    { *m = SvcRequest{} }
func (m *SvcRequest) String() string            { return proto.CompactTextString(m) }
func (*SvcRequest) ProtoMessage()               {}
func (*SvcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SvcResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SvcResponse) Reset()                    { *m = SvcResponse{} }
func (m *SvcResponse) String() string            { return proto.CompactTextString(m) }
func (*SvcResponse) ProtoMessage()               {}
func (*SvcResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SvcResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SvcRequest)(nil), "helloworld.SvcRequest")
	proto.RegisterType((*SvcResponse)(nil), "helloworld.SvcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Svc service

type SvcClient interface {
	Hello(ctx context.Context, in *SvcRequest, opts ...grpc.CallOption) (*SvcResponse, error)
	World(ctx context.Context, in *SvcRequest, opts ...grpc.CallOption) (*SvcResponse, error)
}

type svcClient struct {
	cc *grpc.ClientConn
}

func NewSvcClient(cc *grpc.ClientConn) SvcClient {
	return &svcClient{cc}
}

func (c *svcClient) Hello(ctx context.Context, in *SvcRequest, opts ...grpc.CallOption) (*SvcResponse, error) {
	out := new(SvcResponse)
	err := grpc.Invoke(ctx, "/helloworld.Svc/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svcClient) World(ctx context.Context, in *SvcRequest, opts ...grpc.CallOption) (*SvcResponse, error) {
	out := new(SvcResponse)
	err := grpc.Invoke(ctx, "/helloworld.Svc/World", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Svc service

type SvcServer interface {
	Hello(context.Context, *SvcRequest) (*SvcResponse, error)
	World(context.Context, *SvcRequest) (*SvcResponse, error)
}

func RegisterSvcServer(s *grpc.Server, srv SvcServer) {
	s.RegisterService(&_Svc_serviceDesc, srv)
}

func _Svc_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SvcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvcServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Svc/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvcServer).Hello(ctx, req.(*SvcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Svc_World_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SvcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvcServer).World(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Svc/World",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvcServer).World(ctx, req.(*SvcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Svc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Svc",
	HandlerType: (*SvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Svc_Hello_Handler,
		},
		{
			MethodName: "World",
			Handler:    _Svc_World_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xf1, 0x70, 0x71, 0x05, 0x97, 0x25, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xa9,
	0x73, 0x71, 0x83, 0x79, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x51, 0x2d,
	0x17, 0x73, 0x70, 0x59, 0xb2, 0x90, 0x15, 0x17, 0xab, 0x07, 0xc8, 0x2c, 0x21, 0x31, 0x3d, 0x24,
	0x5b, 0x10, 0x06, 0x4a, 0x89, 0x63, 0x88, 0x43, 0x8c, 0x56, 0x62, 0x00, 0xe9, 0x0d, 0x07, 0x09,
	0x93, 0xa1, 0x37, 0x89, 0x0d, 0xec, 0x11, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xdb,
	0xf5, 0xb1, 0xdc, 0x00, 0x00, 0x00,
}
