{
 "title": "Linkerd Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "h1app",
    "query": "label_values(requests{job=\"slow-cooker\"}, app)"
   },
   {
    "name": "h2app",
    "query": "label_values(requests{job=\"strest-client\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>REQUEST METRICS - HTTP/1</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(successes{job=\"slow-cooker\"}[1m])) by (app) / sum(rate(requests{job=\"slow-cooker\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{job=\"slow-cooker\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P50 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_us_bucket{job=\"slow-cooker\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P90 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(latency_us_bucket{job=\"slow-cooker\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_us_bucket{job=\"slow-cooker\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P99 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_us_bucket{job=\"slow-cooker\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>CONTAINER METRICS - HTTP/1</span>\n</div>"
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=~\"$h1app\", pod_name=~\"(.*)-h1-(.*)\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$h1app\", pod_name=~\"(.*)-h1-(.*)\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>REQUEST METRICS - HTTP/2</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(successes{job=\"strest-client\"}[1m])) by (app) / sum(rate(requests{job=\"strest-client\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{job=\"strest-client\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P50 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_us_bucket{job=\"strest-client\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P90 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(latency_us_bucket{job=\"strest-client\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_us_bucket{job=\"strest-client\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P99 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_us_bucket{job=\"strest-client\"}[1m])) by (le, app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>CONTAINER METRICS - HTTP/2</span>\n</div>"
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=~\"$h2app\", pod_name=~\"(.*)-h2-(.*)\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$h2app\", pod_name=~\"(.*)-h2-(.*)\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}