apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: demo
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.0.4
    helm:
      parameters:
      - name: installCRDs
        value: "true"
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - Validate=false
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
