apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: demo
  source:
    chart: sealed-secrets
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 1.10.3
